export const exercises = [
    "Push-ups",
    "Squats",
    "Lunges",
    "Plank",
    "Deadlifts",
    "Bench press",
    "Burpees",
    "Jumping jacks",
    "Sit-ups",
    "Russian twists",
    "Leg press",
    "Calf raises",
    "Tricep dips",
    "Mountain climbers",
    "Pull-ups",
    "Chin-ups",
    "Dumbbell curls",
    "Overhead press",
    "Dumbbell flyes",
    "Bent-over rows",
    "Lat pulldowns",
    "Hammer curls",
    "Bicep curls",
    "Leg curls",
    "Leg extensions",
    "Single leg barbell romanian deadlift",
    "Single leg dumbbel romanian deadlift",
    "Leg press calf raises",
    "Seated calf raises",
    "Poliquan squats",
    "Nordic hamstring curls",
    "Romanian Deadlifts",
    "Reverse lunges",
    "Step-ups",
    "Incline bench press",
    "Decline bench press",
    "Barbell squats",
    "Front squats",
    "Box jumps",
    "Shoulder press",
    "Arnold press",
    "Upright rows",
    "Lateral raises",
    "Cable flyes",
    "Cable curls",
    "Cable tricep pushdowns",
    "Seated rows",
    "Bent-over flyes",
    "Ab wheel rollouts",
    "Hanging leg raises",
    "Flutter kicks",
    "Cobra pose",
    "Bridge",
    "Dolphin pose",
    "Plank jacks",
    "Scissor kicks",
    "Diamond push-ups",
    "Pike push-ups",
    "Lateral lunges",
    "Bear crawl",
    "Crab walk",
    "Boxing",
    "Kickboxing",
    "Muay Thai",
    "Judo",
    "Karate",
    "Taekwondo",
    "Yoga",
    "Pilates",
    "Zumba",
    "Spinning",
    "Running",
    "Jogging",
    "Walking",
    "Swimming",
    "Cycling",
    "Elliptical training",
    "Rowing",
    "Jump rope",
    "Sprints",
    "Boxing bag work",
    "Battle ropes",
    "Kettlebell swings",
    "Medicine ball slams",
    "Medicine ball twists",
    "Bosu ball exercises",
    "Resistance band exercises",
    "Bodyweight exercises",
    "HIIT workouts",
    "Tabata workouts",
    "Plyometric exercises",
    "Isometric exercises",
    "Calisthenics",
    "Crossfit workouts",
    "Functional training",
    "Gymnastics",
    "Parkour",
    "Rock climbing",
    "Hiking",
    "Kayaking",
    "Surfing",
    "Snowboarding",
    "Skiing",
    "Dancing",
    "Jumping on a trampoline"
  ];
  
  